# Generated by Django 4.1.3 on 2022-11-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('description', models.TextField(max_length=1500)),
                ('category', models.CharField(choices=[('Indoor', 'Indoor'), ('Out door', 'Out door')], max_length=20)),
                ('brand', models.CharField(max_length=20)),
            ],
        ),
    ]
