# Generated by Django 4.1.3 on 2022-11-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_color_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
